name: caremixer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.1.0
  dio: ^5.7.0
  retrofit: ^4.4.1
  go_router: ^16.0.0
  flutter_riverpod: ^2.6.1

  logging: ^1.3.0
  cached_network_image: ^3.4.1
  freezed_annotation: ^2.4.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  # json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4


flutter:
  uses-material-design: true
